import type { Prisma, PrismaClient } from "@/generated/prisma";

// Platform audit primitive (Master Prompt Phần 3 mục XCIV-XCVIII). Action
// names business-readable, actor luôn bắt buộc (không có "system" cho thao
// tác của user). Gọi bên trong CÙNG transaction với state change khi khả
// thi — mục XCVI: không để "Company suspended thành công" nhưng audit ghi
// thất bại âm thầm.
export const AUDIT_ACTIONS = {
  ECOSYSTEM_CREATED: "ECOSYSTEM_CREATED",
  COMPANY_CREATED: "COMPANY_CREATED",
  COMPANY_SUSPENDED: "COMPANY_SUSPENDED",
  COMPANY_RESUMED: "COMPANY_RESUMED",
  COMPANY_ARCHIVED: "COMPANY_ARCHIVED",
  COMPANY_MEMBER_ADDED: "COMPANY_MEMBER_ADDED",
  COMPANY_MEMBER_ROLE_CHANGED: "COMPANY_MEMBER_ROLE_CHANGED",
  COMPANY_MEMBER_REMOVED: "COMPANY_MEMBER_REMOVED",
  LOGIN_SUCCEEDED: "LOGIN_SUCCEEDED",
  LOGIN_FAILED: "LOGIN_FAILED",
  // Phần 4 — Organization + Work Core + Project (mục CXXXIV)
  ORG_UNIT_CREATED: "ORG_UNIT_CREATED",
  ORG_UNIT_ARCHIVED: "ORG_UNIT_ARCHIVED",
  POSITION_CREATED: "POSITION_CREATED",
  POSITION_ARCHIVED: "POSITION_ARCHIVED",
  ASSIGNMENT_CREATED: "ASSIGNMENT_CREATED",
  ASSIGNMENT_ENDED: "ASSIGNMENT_ENDED",
  WORK_CREATED: "WORK_CREATED",
  WORK_ASSIGNED: "WORK_ASSIGNED",
  WORK_STARTED: "WORK_STARTED",
  WORK_COMPLETED: "WORK_COMPLETED",
  WORK_CANCELLED: "WORK_CANCELLED",
  PROJECT_CREATED: "PROJECT_CREATED",
  PROJECT_UPDATED: "PROJECT_UPDATED",
  PROJECT_COMPLETED: "PROJECT_COMPLETED",
  PROJECT_ARCHIVED: "PROJECT_ARCHIVED",
  PROJECT_MEMBER_ADDED: "PROJECT_MEMBER_ADDED",
  // Phần 5 — CRM + Sales + Appointment (mục CXX/CXXI — danh sách đóng, không
  // audit từng keystroke).
  CUSTOMER_CREATED: "CUSTOMER_CREATED",
  CUSTOMER_UPDATED: "CUSTOMER_UPDATED",
  CUSTOMER_OWNER_CHANGED: "CUSTOMER_OWNER_CHANGED",
  CUSTOMER_ARCHIVED: "CUSTOMER_ARCHIVED",
  LEAD_CREATED: "LEAD_CREATED",
  LEAD_CONVERTED: "LEAD_CONVERTED",
  APPOINTMENT_CREATED: "APPOINTMENT_CREATED",
  APPOINTMENT_RESCHEDULED: "APPOINTMENT_RESCHEDULED",
  APPOINTMENT_COMPLETED: "APPOINTMENT_COMPLETED",
  APPOINTMENT_CANCELLED: "APPOINTMENT_CANCELLED",
  APPOINTMENT_NO_SHOW: "APPOINTMENT_NO_SHOW",
  SALE_CREATED: "SALE_CREATED",
  SALE_CONFIRMED: "SALE_CONFIRMED",
  SALE_UPDATED: "SALE_UPDATED",
  SALE_CANCELLED: "SALE_CANCELLED",
  CATALOG_ITEM_CREATED: "CATALOG_ITEM_CREATED",
  CATALOG_ITEM_UPDATED: "CATALOG_ITEM_UPDATED",
  // Phần 6 — Finance + Payroll + Commission + Inventory (HIGH/VERY HIGH
  // RISK — audit trail đầy đủ hơn mức "best-effort" của legacy, xem
  // RED_TEAM_CODE_REVIEW_PART5.md khảo cổ mục audit.ts legacy).
  PAYMENT_RECORDED: "PAYMENT_RECORDED",
  PAYMENT_VOIDED: "PAYMENT_VOIDED",
  EXPENSE_RECORDED: "EXPENSE_RECORDED",
  EXPENSE_VOIDED: "EXPENSE_VOIDED",
  LEDGER_CORRECTION_CREATED: "LEDGER_CORRECTION_CREATED",
  PAYROLL_PROFILE_SET: "PAYROLL_PROFILE_SET",
  PAYROLL_RUN_CREATED: "PAYROLL_RUN_CREATED",
  PAYROLL_RUN_CALCULATED: "PAYROLL_RUN_CALCULATED",
  PAYROLL_RUN_APPROVED: "PAYROLL_RUN_APPROVED",
  PAYROLL_RUN_FINALIZED: "PAYROLL_RUN_FINALIZED",
  PAYROLL_RUN_VOIDED: "PAYROLL_RUN_VOIDED",
  PAYROLL_ITEM_ADJUSTED: "PAYROLL_ITEM_ADJUSTED",
  COMMISSION_RULE_CREATED: "COMMISSION_RULE_CREATED",
  COMMISSION_RULE_UPDATED: "COMMISSION_RULE_UPDATED",
  COMMISSION_CALCULATED: "COMMISSION_CALCULATED",
  COMMISSION_OVERRIDDEN: "COMMISSION_OVERRIDDEN",
  APPROVAL_REQUESTED: "APPROVAL_REQUESTED",
  APPROVAL_FIRST_APPROVED: "APPROVAL_FIRST_APPROVED",
  APPROVAL_RESOLVED: "APPROVAL_RESOLVED",
  APPROVAL_REJECTED: "APPROVAL_REJECTED",
  INVENTORY_ITEM_CREATED: "INVENTORY_ITEM_CREATED",
  INVENTORY_ITEM_UPDATED: "INVENTORY_ITEM_UPDATED",
  INVENTORY_LOCATION_CREATED: "INVENTORY_LOCATION_CREATED",
  STOCK_RECEIVED: "STOCK_RECEIVED",
  STOCK_ISSUED: "STOCK_ISSUED",
  STOCK_TRANSFERRED: "STOCK_TRANSFERRED",
  STOCK_ADJUSTED: "STOCK_ADJUSTED",

  // Phần 7 — Healthcare Vertical
  COMPANY_MODULE_ENABLED: "COMPANY_MODULE_ENABLED",
  COMPANY_MODULE_DISABLED: "COMPANY_MODULE_DISABLED",
  PERMISSION_PACK_GRANTED: "PERMISSION_PACK_GRANTED",
  PERMISSION_PACK_REVOKED: "PERMISSION_PACK_REVOKED",
  MEDICAL_CASE_CREATED: "MEDICAL_CASE_CREATED",
  MEDICAL_CASE_UPDATED: "MEDICAL_CASE_UPDATED",
  MEDICAL_CASE_CLOSED: "MEDICAL_CASE_CLOSED",
  MEDICAL_CASE_REOPENED: "MEDICAL_CASE_REOPENED",
  CONSULTATION_CREATED: "CONSULTATION_CREATED",
  CONSULTATION_UPDATED: "CONSULTATION_UPDATED",
  CONSULTATION_FINALIZED: "CONSULTATION_FINALIZED",
  CONSULTATION_ADDENDUM_ADDED: "CONSULTATION_ADDENDUM_ADDED",
  SCREENING_RECORDED: "SCREENING_RECORDED",
  PROCEDURE_PLANNED: "PROCEDURE_PLANNED",
  PROCEDURE_STARTED: "PROCEDURE_STARTED",
  PROCEDURE_COMPLETED: "PROCEDURE_COMPLETED",
  PROCEDURE_CANCELLED: "PROCEDURE_CANCELLED",
  PROCEDURE_MATERIAL_RECORDED: "PROCEDURE_MATERIAL_RECORDED",
  PROCEDURE_MATERIAL_REVERSED: "PROCEDURE_MATERIAL_REVERSED",
  CONSENT_TEMPLATE_CREATED: "CONSENT_TEMPLATE_CREATED",
  CONSENT_TEMPLATE_ARCHIVED: "CONSENT_TEMPLATE_ARCHIVED",
  CONSENT_CREATED: "CONSENT_CREATED",
  CONSENT_SIGNED: "CONSENT_SIGNED",
  CONSENT_REVOKED: "CONSENT_REVOKED",
  CLINICAL_PHOTO_UPLOADED: "CLINICAL_PHOTO_UPLOADED",
  CLINICAL_PHOTO_ARCHIVED: "CLINICAL_PHOTO_ARCHIVED",
  MEDICAL_FOLLOWUP_CREATED: "MEDICAL_FOLLOWUP_CREATED",
  MEDICAL_FOLLOWUP_UPDATED: "MEDICAL_FOLLOWUP_UPDATED",
  MEDICAL_FOLLOWUP_CLOSED: "MEDICAL_FOLLOWUP_CLOSED",
} as const;

export type AuditAction = (typeof AUDIT_ACTIONS)[keyof typeof AUDIT_ACTIONS];

type AuditParams = {
  actorUserId: string;
  action: AuditAction;
  targetType: string;
  targetId: string;
  ecosystemId?: string;
  companyId?: string;
  metadata?: Record<string, unknown>;
};

// Nhận tx client (Prisma.TransactionClient) hoặc client thường — cho phép
// gọi trong $transaction() của action gọi nó.
export async function recordAudit(
  client: PrismaClient | Prisma.TransactionClient,
  params: AuditParams,
): Promise<void> {
  await client.auditEvent.create({
    data: {
      actorUserId: params.actorUserId,
      action: params.action,
      targetType: params.targetType,
      targetId: params.targetId,
      ecosystemId: params.ecosystemId,
      companyId: params.companyId,
      metadata: params.metadata as Prisma.InputJsonValue | undefined,
    },
  });
}
